### ISSUE TITLE
Remove multipath from GS backup

### ISSUE THREAD

**Issue by blbowles** [ppkhoa/ddn-config-backup#5]
Remove multipath from backup so that it isn't restored over a more recent version of multipath on the NSD sever.

**Comment by ppkhoa** [comment]
Addressed in #6ec76738bd550445aa2807ba7cf4b30932bfbed2. Closing this issue

**Comment by ppkhoa** [comment]
Addressed in commit 6ec76738bd550445aa2807ba7cf4b30932bfbed2. Closing this issue
