### ISSUE TITLE
Feature Request: Have script leave copy of itself in GS backup files

### ISSUE THREAD

**Issue by wnesemeier** [ppkhoa/ddn-config-backup#6]
on a recent upgrade we experienced some complication with bringing the script back to the recently re-imaged NSDs, due to a relatively complex network security environment and broken ssh keys. It would have been convenient if the backup files included a copy of the script.

**Comment by ppkhoa** [comment]
Added in b6a5b0e4e30a0edcca300cfbf8059eaf69601ec2. Closing request
