### ISSUE TITLE
Enhancements to gs_restore

### ISSUE THREAD

**Issue by aaronknister** [ppkhoa/ddn-config-backup#9]
The sshkeyscan process could take a long time for large clusters, so why not skip by default and allow the user to re-run the script with the `-e` option if they'd like to do that. 

It's probably also beneficial to print the `mmsdrrestore` message after a gs_restore to remind the end user to perform that step.

I'll send over a PR for both in just a moment.

**Comment by ppkhoa** [comment]
Thanks for your suggestion, @aaronknister! 

For #10: User can run the script with -s flag to scan for SSH keys separately, I can merge your pull request.

For #11: Usually that step is mentioned in the upgrade plan (script is provided with the upgrade plan if it's a reimage). Doesn't hurt to make sure they don't skip that step.
